version: '3'

tasks:
  activate:
    dir: venv/Scripts
    cmds:
      - activate.bat
  install:
    cmds:
      - pip install D:/Development/projects/sealights/SL.OnPremise.Agents.Python
  bsid:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python config --appname calc-demo-python --exclude "*tests*,*venv*"
  scan:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python scan --buildsessionidfile ./buildSessionId.txt
  unittest:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python unittest --buildsessionidfile ./buildSessionId.txt --teststage stage3
  pytest:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python pytest --buildsessionidfile ./buildSessionId.txt --teststage stage3
  nose:
    env:
      SL_DEBUG: true
    cmds:
      - sl-python nose --buildsessionidfile ./buildSessionId.txt --teststage stage3  ./tests/nose/test_main.py
  start:
    cmds:
      - sl-python start --buildsessionidfile ./buildSessionId.txt --teststage stage1 --testgroupid groupid
  end:
    cmds:
      - sl-python end --buildsessionidfile ./buildSessionId.txt --teststage stage1 --testgroupid groupid
  run:
    env:
      SL_DEBUG: true
    cmds:
      - sl-python run --buildsessionidfile ./buildSessionId.txt python ./main.py