version: '3'

tasks:
  activate:
    dir: venv/Scripts
    cmds:
      - activate.bat
  install:
    cmds:
      - pip install D:/Development/projects/sealights/SL.OnPremise.Agents.Python
  bsid:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python config --appname calc-demo-python --exclude "*tests*,*venv*"
  scan:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python scan --buildsessionidfile ./buildSessionId.txt
  unittest:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python unittest --buildsessionidfile ./buildSessionId.txt --teststage stage1
  pytest:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python pytest --buildsessionidfile ./buildSessionId.txt --teststage stage2
  nose:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python nose --buildsessionidfile ./buildSessionId.txt --teststage stage3  ./tests/nose/test_main.py
  start:
    cmds:
      - sl-python start --buildsessionidfile ./buildSessionId.txt --teststage stage1 --testgroupid groupid
  end:
    cmds:
      - sl-python end --buildsessionidfile ./buildSessionId.txt --teststage stage1 --testgroupid groupid
  run:
    env:
      SL_DEBUG: true
    cmds:
      - sl-python run --buildsessionidfile ./buildSessionId.txt python ./main.py
  pcf:
    cmds:
      - cf target -o "system" -s "sealights"
      - cf push calc-demo -b https://github.com/cloudfoundry/python-buildpack.git
  pcf-local:
    cmds:
      - cf target -o "system" -s "sealights"
#      - cf push calc-demo -b file://D:/Development/projects/sealights/python-buildpack
      - cf push calc-demo -b https://github.com/liornabat-sealights/python-buildpack.git
  pcf-service:
    cmds:
      - cf cups sealights -p pcf_service.json
  pcf-ci:
    cmds:
#      - task: install
#      - task: bsid
#      - task: scan
      - task: pcf-local
      - cf bs calc-demo sealights
      - cf restage calc-demo