version: '3'

tasks:
  activate:
    dir: venv/Scripts
    cmds:
      - activate.bat
  install:
    cmds:
      - pip install D:/Development/projects/sealights/SL.OnPremise.Agents.Python
  pip:
    cmds:
      - pip install -r requirements_sealights.txt
  bsid:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python config --appname calc-demo-python --tokenfile ./sltoken.txt --exclude "*tests*,*venv*"
  prbsid:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python prconfig --appname calc-demo-python --tokenfile ./sltoken.txt --exclude "*tests*,*venv*" --targetbranch main --latestcommit asd3asd --pullrequestnumber 123 --repourl dasdasdasdas
  scan:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python scan --buildsessionidfile ./buildSessionId.txt --tokenfile ./sltoken.txt
  unittest:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python unittest --buildsessionidfile ./buildSessionId.txt --tokenfile ./sltoken.txt --teststage stage1
  pytest:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python pytest --buildsessionidfile ./buildSessionId.txt --tokenfile ./sltoken.txt --teststage stage3 --testgroupid groupid
  nose:
    env:
#      SL_DEBUG: true
    cmds:
      - sl-python nose --buildsessionidfile ./buildSessionId.txt --tokenfile ./sltoken.txt --teststage stage3  ./tests/nose/test_main.py
  start:
    cmds:
      - sl-python start --buildsessionidfile ./buildSessionId.txt --tokenfile ./sltoken.txt --teststage stage1 --testgroupid groupid
  end:
    cmds:
      - sl-python end --buildsessionidfile ./buildSessionId.txt --tokenfile ./sltoken.txt --teststage stage1 --testgroupid groupid
  run:
    env:
      SL_DEBUG: true
    cmds:
      - sl-python run --buildsessionidfile ./buildSessionId.txt --tokenfile ./sltoken.txt python ./main.py
  run-module:
    env:
      SL_DEBUG: true
    cmds:
      - sl-python run --buildsessionidfile ./buildSessionId.txt --tokenfile ./sltoken.txt python -m local_dev.flask_run
  pcf:
    cmds:
      - cf target -o "system" -s "sealights"
      - cf push calc-demo -b https://github.com/cloudfoundry/python-buildpack.git
  pcf-local:
    cmds:
      - cf target -o "system" -s "sealights"
#      - cf push calc-demo -b file://D:/Development/projects/sealights/python-buildpack
      - cf push calc-demo -b https://github.com/liornabat-sealights/python-buildpack.git
  pcf-service:
    cmds:
      - cf cups sealights -p pcf_service.json
  pcf-ci:
    cmds:
      - task: install
      - task: bsid
      - task: scan
      - task: pcf-local
      - cf bs calc-demo sealights
      - cf restage calc-demo
  ci:
    cmds:
      - task: install
      - task: bsid
      - task: scan
      - task: pytest

# Important - python pcf buildpack need more setting after creating the env:
# Enable TCP routing in Networking
# Apply again the setting
# run cf create-shared-domain tcp.[ENV-NAME].cf-app.com --router-group default-tcp
